import pytest
from playwright.sync_api import expect
EXPECTED_URL_AFTER_LOGIN = "https://www.saucedemo.com/inventory.html"
def test_login(page):
    page.goto("https://www.saucedemo.com/")
    page.fill("#user-name", "standard_user")
    page.fill("#password", "secret_sauce")
    page.screenshot(path="login_page.png")
    page.click("#login-button")
    page.screenshot(path="after_login.png")
    expect(page).to_have_url(EXPECTED_URL_AFTER_LOGIN)
    expect(page).to_have_title("Swag Labs")
    print(page.title())
    #expect(page.get_by_role("heading", name="Swag Labs")).to_be_visible()
    expect(page.locator(".title")).to_have_text("Products")
    page.click("#add-to-cart-sauce-labs-bolt-t-shirt")
    page.click("#add-to-cart-sauce-labs-fleece-jacket")
    page.screenshot(path="after_adding_to_cart.png")
    page.click("#shopping_cart_container")
    page.screenshot(path="cart_page.png")
    page.click("[name='continue-shopping']")
    page.screenshot(path="after_continue_shopping.png")
    page.click("[name='add-to-cart-sauce-labs-onesie']")
    page.screenshot(path="after_adding_onesie.png")
    page.click("#shopping_cart_container")
    page.screenshot(path="final_cart_page.png")
    page.click("#checkout")
    page.screenshot(path="after_clicking_checkout.png")
    page.get_by_placeholder("First Name").fill("Mark")
    page.fill("[id='last-name']","Antony")
    page.fill("[id='postal-code']","12345")
    page.screenshot(path="after_filling_checkout_info.png")
    page.click("[name='cancel']")
    page.wait_for_selector("#checkout")
    page.wait_for_load_state("domcontentloaded")
    page.screenshot(path="after_clicking_cancel.png")
    expect(page.locator("#checkout")).to_be_enabled()
    page.click("#checkout")
    page.screenshot(path="after_clicking_checkout_again.png")
    expect(page.locator(".title")).to_have_text("Checkout: Your Information")
    page.get_by_placeholder("First Name").fill("Mark")
    page.get_by_placeholder("Last Name").fill("Antony")
    page.fill("[id='postal-code']","12345")
    page.screenshot(path="after_filling_checkout_info_again.png")
    page.get_by_text("Continue").click()
    #page.click("[name='continue']")
    expect(page.locator(".title")).to_have_text("Checkout: Overview")
    page.screenshot(path="after_clicking_continue.png")
    page.locator("xpath=//*[@name='finish']").click()
    #page.get_by_role("button",name="Finish").click()
    page.screenshot(path="after_clicking_finish.png")
    page.close()
